/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package newpath.telas;

import dao.ContadorDao;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import modelo.Contador;

/**
 *
 * @author hmq48
 */
public class TelaEstimativaDeEconomia extends javax.swing.JFrame {
    public String loginUsuario;
    /** Creates new form TelaEstimativaDeEconomia */
    public TelaEstimativaDeEconomia() {
        initComponents();
        getContentPane().setBackground(new Color(30, 30, 30));
    }
    
    public TelaEstimativaDeEconomia(String loginUsuario){
        initComponents();
        getContentPane().setBackground(new Color(30, 30, 30));
        this.loginUsuario = loginUsuario;
        
        java.sql.Date dataEntrada;
            LocalDate  atualData = LocalDate.now(); 
            try {
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                String dataStr = atualData.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")); 
                dataEntrada = new java.sql.Date(format.parse(dataStr).getTime());
            } 
        
            catch (ParseException e) {
                throw new RuntimeException(e);
            }
        Contador contador = new Contador();
        contador.setLogin(loginUsuario);
        ContadorDao contadorDao = new ContadorDao();
        Contador contadorComData = contadorDao.getDataAtualByLogin(loginUsuario);
        Date dataAtual = contadorComData.getDataAtual();
        String vicio = contadorComData.getVicio();
        if (dataAtual == null){
            LocalDate atualData2 = LocalDate.now(); 
            try {
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                String dataStr = atualData2.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")); 
                dataAtual = new java.sql.Date(format.parse(dataStr).getTime());
                
            } 
            
            catch (ParseException e) {
                throw new RuntimeException(e);
            }
        }
        long diferencaMillis = dataEntrada.getTime() - dataAtual.getTime();
        long diasSobriedade = TimeUnit.MILLISECONDS.toDays(diferencaMillis);
        String diasSobriedadeStr = String.valueOf(diasSobriedade);
        int diasSobriedadeInt = (int) diasSobriedade; 
        if (vicio == null){
            vicio = "Drogas";
        }
        lblPergunta.setText("Quanto em média você gastava por dia com " + vicio + "?");
        
        
        
            
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollBar1 = new javax.swing.JScrollBar();
        jMenuItem1 = new javax.swing.JMenuItem();
        lblPergunta = new javax.swing.JLabel();
        txtGasto = new javax.swing.JTextField();
        lblFavor = new javax.swing.JLabel();
        btnChecar = new GradientButton("Checar");
        lblFinal = new javax.swing.JLabel();
        btnFechar = new GradientButton1("Fechar");
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 30, 30));

        lblPergunta.setForeground(new java.awt.Color(255, 255, 255));
        lblPergunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPergunta.setText("Quanto, em média, você gastava com *********?");

        txtGasto.setBackground(new java.awt.Color(50, 50, 50));
        txtGasto.setForeground(new java.awt.Color(255, 255, 255));
        txtGasto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGasto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGastoActionPerformed(evt);
            }
        });

        lblFavor.setForeground(new java.awt.Color(255, 255, 255));
        lblFavor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFavor.setText("(Favor inserir apenas números)");

        btnChecar.setText("Checar");
        btnChecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChecarActionPerformed(evt);
            }
        });

        lblFinal.setForeground(new java.awt.Color(255, 255, 255));
        lblFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinal.setText("Você economizou ** reais em ** Dias de sobriedade!");

        btnFechar.setText("Fechar");
        btnFechar.setActionCommand("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jMenu3.setText("Estimativa de Economia");
        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(txtGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnChecar)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFechar)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPergunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFavor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblPergunta)
                .addGap(1, 1, 1)
                .addComponent(lblFavor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChecar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(lblFinal)
                .addGap(40, 40, 40)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGastoActionPerformed

    private void btnChecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChecarActionPerformed
        // TODO add your handling code here:
        String valor = txtGasto.getText();
        
        java.sql.Date dataEntrada;
            LocalDate  atualData = LocalDate.now(); 
            try {
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                String dataStr = atualData.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")); 
                dataEntrada = new java.sql.Date(format.parse(dataStr).getTime());
            } 
        
            catch (ParseException e) {
                throw new RuntimeException(e);
            }
        Contador contador = new Contador();
        contador.setLogin(loginUsuario);
        ContadorDao contadorDao = new ContadorDao();
        Contador contadorComData = contadorDao.getDataAtualByLogin(loginUsuario);
        Date dataAtual = contadorComData.getDataAtual();
        String vicio = contadorComData.getVicio();
        if (dataAtual == null){
            LocalDate atualData2 = LocalDate.now(); 
            try {
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                String dataStr = atualData2.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")); 
                dataAtual = new java.sql.Date(format.parse(dataStr).getTime());
                
            } 
            
            catch (ParseException e) {
                throw new RuntimeException(e);
            }
        }
        long diferencaMillis = dataEntrada.getTime() - dataAtual.getTime();
        long diasSobriedade = TimeUnit.MILLISECONDS.toDays(diferencaMillis);
        String diasSobriedadeStr = String.valueOf(diasSobriedade);
        int diasSobriedadeInt = (int) diasSobriedade;
        int valorInt = Integer.parseInt(valor);  
        int economia = valorInt * diasSobriedadeInt;
        lblFinal.setText("Você economizou R$" + economia + " em " + diasSobriedadeInt + " dias de sobriedade");
        
    }//GEN-LAST:event_btnChecarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstimativaDeEconomia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstimativaDeEconomia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstimativaDeEconomia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstimativaDeEconomia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstimativaDeEconomia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChecar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel lblFavor;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JTextField txtGasto;
    // End of variables declaration//GEN-END:variables

}
