/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpath.telas;

import dao.NotasDao;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Contato;
import modelo.Notas;

/**
 *
 * @author hmq48
 */
public class TelaNotas extends javax.swing.JFrame {
     private String loginUsuario;
     
     

    /**
     * Creates new form TelaNotas
     */
    public TelaNotas() {
        initComponents();
    }
    public TelaNotas(String loginUsuario) {
        initComponents();
        getContentPane().setBackground(new Color(40, 40, 40));
        tblNotas.setShowGrid(true);
        tblNotas.setGridColor(Color.BLACK);
        
        
        DefaultTableCellRenderer centralizar = new DefaultTableCellRenderer();
        centralizar.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < tblNotas.getColumnCount(); i++) {
            tblNotas.getColumnModel().getColumn(i).setCellRenderer(centralizar);
        }
        
        
        this.loginUsuario = loginUsuario;
        tblNotas.getColumnModel().getColumn(0).setMinWidth(0);
        tblNotas.getColumnModel().getColumn(0).setMaxWidth(0);
        tblNotas.getColumnModel().getColumn(0).setWidth(0);
        tblNotas.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblNotas.rowAtPoint(evt.getPoint());
        int column = tblNotas.columnAtPoint(evt.getPoint());

        
        if (column == 2 && row != -1) {
            Object valor = tblNotas.getValueAt(row, column);
            if (valor != null) {
                String descricao = valor.toString();
                javax.swing.JOptionPane.showMessageDialog(
                    null,
                    descricao,
                    "Descrição Completa",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );
            }
        }
    }
});
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        lblListaVazia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNotas = new javax.swing.JTable();
        btnAdicionarNota = new GradientButton ("AdicionarNota");
        btnExcluirNota = new GradientButton1("Excluir Nota");
        btnModificarNota = new GradientButton("Modificar");
        btnRecarregar = new GradientButton("Recarregar");
        btnVoltar = new GradientButton1("Voltar");
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        jCheckBox1.setText("jCheckBox1");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(40, 40, 40));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblListaVazia.setForeground(new java.awt.Color(255, 255, 255));
        lblListaVazia.setText("jLabel1");

        tblNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo", "Descrição", "Data de postagem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNotas);

        btnAdicionarNota.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarNota.setText("Adicionar Nota");
        btnAdicionarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarNotaActionPerformed(evt);
            }
        });

        btnExcluirNota.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirNota.setText("Excluir Nota");
        btnExcluirNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirNotaActionPerformed(evt);
            }
        });

        btnModificarNota.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarNota.setText("Modificar Nota");
        btnModificarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarNotaActionPerformed(evt);
            }
        });

        btnRecarregar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecarregar.setText("Recarregar");
        btnRecarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecarregarActionPerformed(evt);
            }
        });

        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jMenu1.setText("Notas");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListaVazia, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVoltar)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAdicionarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnModificarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnExcluirNota, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnRecarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaVazia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarNota)
                    .addComponent(btnExcluirNota)
                    .addComponent(btnModificarNota)
                    .addComponent(btnRecarregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltar)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btnAdicionarNota.getAccessibleContext().setAccessibleName("");
        btnExcluirNota.getAccessibleContext().setAccessibleName("");
        btnModificarNota.getAccessibleContext().setAccessibleName("");
        btnRecarregar.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        NotasDao notasDao = new NotasDao();
        List<Notas> lista = notasDao.buscarNotasPorUsuario(loginUsuario);
        if(lista.isEmpty()){
            lblListaVazia.setVisible(true);
            lblListaVazia.setText("Nenhuma nota encontrada, adicione uma nova nota!");
        }
        else {
            lblListaVazia.setVisible(false);
            lblListaVazia.setText("Aqui estão suas notas! Adicione outras ou edite as existentes!");
            for (Notas notas: lista) {
            DefaultTableModel model = (DefaultTableModel) tblNotas.getModel();
            model.addRow(new Object[] {
            notas.getId(),
            notas.getTitulo(),
            notas.getDescricao(),
            notas.getDataRegistro(),
             });
        }
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btnAdicionarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarNotaActionPerformed
        // TODO add your handling code here:
        int id = 0;
                    
        TelaAdicionaNota telaAdicionaNota = new TelaAdicionaNota(loginUsuario, id);
        
        telaAdicionaNota.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnAdicionarNotaActionPerformed

    private void btnRecarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecarregarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaNotas(loginUsuario).setVisible(true);


               
    }//GEN-LAST:event_btnRecarregarActionPerformed

    private void btnModificarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarNotaActionPerformed
        // TODO add your handling code here:
       
         if (tblNotas.getSelectedRowCount() == 1){
            int row = tblNotas.getSelectedRow();
            int id = Integer.parseInt (
                    tblNotas.getValueAt(row, 0).toString());
                new TelaAdicionaNota(id).setVisible(true);
               
        }
        else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma linha!");
        }
        
        
    }//GEN-LAST:event_btnModificarNotaActionPerformed

    private void btnExcluirNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirNotaActionPerformed
        // TODO add your handling code here:
            if (tblNotas.getSelectedRowCount() == 1) {
            Integer row = tblNotas.getSelectedRow();
            Integer id = Integer.valueOf(
                    tblNotas.getValueAt(row, 0).toString());
            Integer resposta = JOptionPane
                        .showConfirmDialog(null,
                                "Deseja realmente excluir?");
            if (resposta == JOptionPane.YES_OPTION) {
                NotasDao notasDao = new NotasDao();
                notasDao.removeNota(id);
                JOptionPane.showMessageDialog(null,
                        "Nota removida com sucesso!");
                DefaultTableModel model = 
                        (DefaultTableModel) tblNotas.getModel();
                model.removeRow(row);
            }
        }
        else {
            JOptionPane.showMessageDialog(null,
                    "Por favor, selecione uma linha!");
        }
    }//GEN-LAST:event_btnExcluirNotaActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal telaPrincipal = new TelaPrincipal(loginUsuario);
        telaPrincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarNota;
    private javax.swing.JButton btnExcluirNota;
    private javax.swing.JButton btnModificarNota;
    private javax.swing.JButton btnRecarregar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListaVazia;
    private javax.swing.JTable tblNotas;
    // End of variables declaration//GEN-END:variables
}
